// ─────────────────────────────────────────────────────────────────────────
// Baby food & infant formula catalog + feeding-amount calculator.
// Data from USDA FoodData Central SR Legacy (food_category_id=3).
// 341 foods: purees, cereals, juices, infant formulas, toddler meals.
// Source: fdc.nal.usda.gov
// ─────────────────────────────────────────────────────────────────────────

const BABY_FOODS = [
  {"name":"Apple yogurt dessert, strained","kcal_100g":93.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Juice, pear","kcal_100g":43.0,"isPowder":false,"tags":["juice"]},
  {"name":"Meat, beef with vegetables, toddler","kcal_100g":69.0,"isPowder":false,"tags":["vegetable", "meat", "toddler"]},
  {"name":"Mixed fruit yogurt, strained","kcal_100g":75.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Rice and apples, dry","kcal_100g":396.0,"isPowder":false,"tags":[]},
  {"name":"Juice, apple - cherry","kcal_100g":47.0,"isPowder":false,"tags":["juice"]},
  {"name":"Cereal, rice with pears and apple, dry, instant fortified","kcal_100g":389.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Banana no tapioca, strained","kcal_100g":91.0,"isPowder":false,"tags":[]},
  {"name":"Banana apple dessert, strained","kcal_100g":68.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Banana juice with low fat yogurt","kcal_100g":86.0,"isPowder":false,"tags":["juice", "dessert"]},
  {"name":"Mixed fruit juice with low fat yogurt","kcal_100g":74.0,"isPowder":false,"tags":["juice", "fruit", "dessert"]},
  {"name":"Dinner, macaroni, beef and tomato sauce, toddler","kcal_100g":82.0,"isPowder":false,"tags":["meat", "dinner", "toddler"]},
  {"name":"Dessert, peach yogurt","kcal_100g":77.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, blueberry yogurt, strained","kcal_100g":77.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, banana yogurt, strained","kcal_100g":78.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Fruit supreme dessert","kcal_100g":73.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Grape juice, no sugar, canned","kcal_100g":62.0,"isPowder":false,"tags":["juice"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Newborn, with ARA and DHA, powd","kcal_100g":516.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Premium LIPIL, Infant, powder","kcal_100g":510.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Premium LIPIL, Infant, Liquid c","kcal_100g":129.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Premium, Infant, Liquid concent","kcal_100g":129.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, ENFAGROW, GENTLEASE, Toddler tr","kcal_100g":500.0,"isPowder":false,"tags":["formula", "toddler"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, GO AND GROW, powder, with A","kcal_100g":512.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, Gerber GOOD START 2 SOY, with iron, powder","kcal_100g":501.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMIGEN, PurAmino, powder, n","kcal_100g":512.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Premature, 20 calories ready-to","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Rice cereal, dry, EARTHS BEST ORGANIC WHOLE GRAIN, fortified only with","kcal_100g":386.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Juice, apple-sweet potato","kcal_100g":47.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange-carrot","kcal_100g":43.0,"isPowder":false,"tags":["juice"]},
  {"name":"Baked product, finger snacks cereal fortified","kcal_100g":421.0,"isPowder":false,"tags":["cereal", "snack"]},
  {"name":"Cereal, brown rice, dry, instant","kcal_100g":406.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Green beans and turkey, strained","kcal_100g":51.0,"isPowder":false,"tags":["meat"]},
  {"name":"Dinner, chicken and rice","kcal_100g":51.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Infant formula, Gerber GOOD START, PROTECT PLUS, powder","kcal_100g":512.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant Formula, GERBER GOOD START 2, GENTLE PLUS, powder","kcal_100g":492.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, Gerber GOOD START 2, PROTECT PLUS, powder","kcal_100g":501.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, ENFAGROW, Soy, Toddler transiti","kcal_100g":476.0,"isPowder":false,"tags":["formula", "toddler"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Premature, 24 calories ready-to","kcal_100g":67.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Premium, Infant, ready-to-feed","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Premium, Infant, powder","kcal_100g":510.0,"isPowder":true,"tags":["formula"]},
  {"name":"Gerber Banana with orange medley","kcal_100g":69.0,"isPowder":false,"tags":[]},
  {"name":"Vegetable and brown rice, strained","kcal_100g":69.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Peas and brown rice","kcal_100g":64.0,"isPowder":false,"tags":[]},
  {"name":"Carrots, toddler","kcal_100g":21.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Dessert, banana pudding, strained","kcal_100g":68.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Fruit, tutti frutti, strained","kcal_100g":66.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, tutti frutti, junior","kcal_100g":69.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fluid replacement, electrolyte solution (include PEDIALYTE)","kcal_100g":10.0,"isPowder":false,"tags":[]},
  {"name":"Vegetables, peas, strained","kcal_100g":50.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Peas, dices, toddler","kcal_100g":64.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Vegetables, spinach, creamed, strained","kcal_100g":37.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Fruit, apricot with tapioca, junior","kcal_100g":63.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, pears, junior","kcal_100g":44.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, plums with tapioca, without ascorbic acid, strained","kcal_100g":71.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, plums with tapioca, without ascorbic acid, junior","kcal_100g":74.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, prunes with tapioca, without ascorbic acid, strained","kcal_100g":69.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, applesauce and apricots, strained","kcal_100g":44.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, applesauce and apricots, junior","kcal_100g":47.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, applesauce and cherries, strained","kcal_100g":51.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, applesauce and cherries, junior","kcal_100g":51.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, applesauce with banana, junior","kcal_100g":66.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit and vegetable, apple and sweet potato","kcal_100g":64.0,"isPowder":false,"tags":["fruit", "vegetable"]},
  {"name":"Fruit, bananas and pineapple with tapioca, junior","kcal_100g":68.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, bananas and pineapple with tapioca, strained","kcal_100g":65.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, pears and pineapple, strained","kcal_100g":41.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, bananas with apples and pears, strained","kcal_100g":83.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, apple and blueberry, strained","kcal_100g":61.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, apple and blueberry, junior","kcal_100g":62.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Juice, apple","kcal_100g":47.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange and apple and banana","kcal_100g":47.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange and apricot","kcal_100g":46.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange and banana","kcal_100g":50.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange and pineapple","kcal_100g":48.0,"isPowder":false,"tags":["juice"]},
  {"name":"Cereal, mixed, dry fortified","kcal_100g":399.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, mixed, with bananas, dry","kcal_100g":391.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, mixed, with applesauce and bananas, strained","kcal_100g":82.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, mixed, with applesauce and bananas, junior, fortified","kcal_100g":84.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, with honey, dry","kcal_100g":391.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, rice, dry fortified","kcal_100g":390.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, rice, with applesauce and bananas, strained","kcal_100g":80.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, with egg yolks, strained","kcal_100g":51.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Crackers, vegetable","kcal_100g":477.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Cereal, high protein, with apple and orange, dry","kcal_100g":374.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, rice, with bananas, dry","kcal_100g":404.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cookies","kcal_100g":433.0,"isPowder":false,"tags":[]},
  {"name":"Dessert, dutch apple, strained","kcal_100g":75.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, dutch apple, junior","kcal_100g":79.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Cherry cobbler, junior","kcal_100g":78.0,"isPowder":false,"tags":[]},
  {"name":"Dessert, cherry vanilla pudding, strained","kcal_100g":68.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, peach melba, strained","kcal_100g":60.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, peach melba, junior","kcal_100g":60.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, fruit pudding, pineapple, strained","kcal_100g":81.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Dessert, fruit dessert, without ascorbic acid, strained","kcal_100g":59.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Juice, fruit punch, with calcium","kcal_100g":52.0,"isPowder":false,"tags":["juice", "fruit"]},
  {"name":"Juice, apple, with calcium","kcal_100g":46.0,"isPowder":false,"tags":["juice"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, ENFACARE, ready-to-feed, with A","kcal_100g":73.0,"isPowder":false,"tags":["formula"]},
  {"name":"Yogurt, whole milk, with fruit, multigrain cereal and added DHA fortif","kcal_100g":98.0,"isPowder":false,"tags":["cereal", "fruit", "dessert"]},
  {"name":"Infant formula, ABBOTT NUTRITION, ALIMENTUM ADVANCE, with iron, powder","kcal_100g":517.0,"isPowder":true,"tags":["formula"]},
  {"name":"Mashed cheddar potatoes and broccoli, toddlers","kcal_100g":48.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Yogurt, whole milk, with fruit, multigrain cereal and added iron forti","kcal_100g":92.0,"isPowder":false,"tags":["cereal", "fruit", "dessert"]},
  {"name":"Infant formula, NESTLE, GOOD START SOY, with DHA and ARA, liquid conce","kcal_100g":132.0,"isPowder":false,"tags":["formula"]},
  {"name":"Toddler formula, MEAD JOHNSON, ENFAGROW, Toddler Transitions, with ARA","kcal_100g":505.0,"isPowder":false,"tags":["formula", "toddler"]},
  {"name":"Toddler formula, MEAD JOHNSON, ENFAGROW PREMIUM (formerly ENFAMIL, LIP","kcal_100g":64.0,"isPowder":false,"tags":["formula", "toddler"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, Newborn, with DHA and ARA, read","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, Gerber GOOD START 2 Soy, with iron, ready-to-feed","kcal_100g":65.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, Gerber GOOD START, PROTECT PLUS, ready-to-feed","kcal_100g":65.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant Formula, GERBER GOOD START 2, GENTLE PLUS, ready-to-feed","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Fruit, banana and strawberry, junior","kcal_100g":109.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Banana with mixed berries, strained","kcal_100g":92.0,"isPowder":false,"tags":[]},
  {"name":"Multigrain whole grain cereal, dry fortified","kcal_100g":407.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Baby MUM MUM Rice Biscuits","kcal_100g":391.0,"isPowder":false,"tags":["snack"]},
  {"name":"Vegetables, corn, creamed, junior","kcal_100g":65.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Fruit, bananas with tapioca, strained","kcal_100g":56.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, peaches, strained","kcal_100g":65.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, peaches, junior","kcal_100g":65.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, pears, strained","kcal_100g":42.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, prunes with tapioca, without ascorbic acid, junior","kcal_100g":70.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Prunes, without vitamin c, strained","kcal_100g":100.0,"isPowder":false,"tags":[]},
  {"name":"Fruit dessert, mango with tapioca","kcal_100g":70.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Pears, dices, toddler","kcal_100g":57.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Fruit, applesauce and pineapple, strained","kcal_100g":37.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, applesauce and pineapple, junior","kcal_100g":39.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, apple and raspberry, strained","kcal_100g":58.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, apple and raspberry, junior","kcal_100g":58.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, pears and pineapple, junior","kcal_100g":44.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, guava and papaya with tapioca, strained","kcal_100g":63.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Peaches, dices, toddler","kcal_100g":51.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Fruit, papaya and applesauce with tapioca, strained","kcal_100g":70.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Apple-banana juice","kcal_100g":51.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, apple and peach","kcal_100g":43.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, apple and prune","kcal_100g":72.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange","kcal_100g":45.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, orange and apple","kcal_100g":43.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, prune and orange","kcal_100g":70.0,"isPowder":false,"tags":["juice"]},
  {"name":"Juice, mixed fruit","kcal_100g":47.0,"isPowder":false,"tags":["juice", "fruit"]},
  {"name":"Cereal, barley, dry fortified","kcal_100g":376.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, whole wheat, with apples, dry fortified","kcal_100g":402.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, dry fortified","kcal_100g":394.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, with bananas, dry","kcal_100g":399.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, with applesauce and bananas, strained","kcal_100g":75.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, with applesauce and bananas, junior, fortified","kcal_100g":76.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, with egg yolks, junior","kcal_100g":52.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, with eggs, strained","kcal_100g":58.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, egg yolks and bacon, junior","kcal_100g":79.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Oatmeal cereal with fruit, dry, instant, toddler fortified","kcal_100g":402.0,"isPowder":false,"tags":["cereal", "fruit", "toddler"]},
  {"name":"Cookie, baby, fruit","kcal_100g":435.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Cookies, arrowroot","kcal_100g":424.0,"isPowder":false,"tags":[]},
  {"name":"Pretzels","kcal_100g":397.0,"isPowder":false,"tags":[]},
  {"name":"Gerber GRADUATES Lil Biscuits Vanilla Wheat","kcal_100g":407.0,"isPowder":false,"tags":["snack"]},
  {"name":"Zwieback","kcal_100g":426.0,"isPowder":false,"tags":[]},
  {"name":"Dessert, cherry vanilla pudding, junior","kcal_100g":69.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, fruit pudding, orange, strained","kcal_100g":80.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Dessert, peach cobbler, strained","kcal_100g":65.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, peach cobbler, junior","kcal_100g":67.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, fruit dessert, without ascorbic acid, junior","kcal_100g":63.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Dessert, tropical fruit, junior","kcal_100g":60.0,"isPowder":false,"tags":["fruit", "dessert"]},
  {"name":"Dessert, custard pudding, vanilla, strained","kcal_100g":85.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Dessert, custard pudding, vanilla, junior","kcal_100g":86.0,"isPowder":false,"tags":["dessert"]},
  {"name":"Juice, apple and grape","kcal_100g":46.0,"isPowder":false,"tags":["juice"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ISOMIL, ADVANCE with iron, ","kcal_100g":517.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, NESTLE, GOOD START SUPREME, with iron, DHA and ARA, re","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, NESTLE, GOOD START SUPREME, with iron, DHA and ARA, pr","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL GENTLEASE, with iron, prepared f","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Fortified cereal bar, fruit filling","kcal_100g":344.0,"isPowder":false,"tags":["cereal", "fruit"]},
  {"name":"Infant Formula, MEAD JOHNSON, ENFAMIL, GENTLEASE, with ARA and DHA pow","kcal_100g":516.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Enfagrow, Soy, Toddler ready-to","kcal_100g":65.0,"isPowder":false,"tags":["formula", "toddler"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMIGEN AA, ready-to-feed","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Premature, with iron, 20 calori","kcal_100g":63.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Premature, with iron, 24 calori","kcal_100g":81.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, Gerber GOOD START 2, PROTECT PLUS, ready-to-feed","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, GO AND GROW, ready-to-feed,","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, Expert Care, Diarrhea, read","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, For Spit Up, ready-to-feed,","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Snack, Gerber Graduates Lil Crunchies, baked whole grain corn snack","kcal_100g":503.0,"isPowder":false,"tags":["snack"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, For Spit Up, powder, with A","kcal_100g":514.0,"isPowder":true,"tags":["formula"]},
  {"name":"Meat, beef, junior","kcal_100g":81.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, veal, strained","kcal_100g":81.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, pork, strained","kcal_100g":124.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, ham, strained","kcal_100g":97.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, chicken, junior","kcal_100g":146.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, chicken sticks, junior","kcal_100g":188.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, turkey, strained","kcal_100g":111.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, turkey, junior","kcal_100g":111.0,"isPowder":false,"tags":["meat"]},
  {"name":"Finger snacks, Gerber Graduates PUFFS, apple and cinnamon","kcal_100g":344.0,"isPowder":false,"tags":["snack"]},
  {"name":"Gerber 3rd Foods, apple, mango and kiwi","kcal_100g":48.0,"isPowder":false,"tags":[]},
  {"name":"Tropical fruit medley","kcal_100g":46.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Dinner, vegetables and dumplings and beef, strained","kcal_100g":48.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Ravioli, cheese filled, with tomato sauce","kcal_100g":99.0,"isPowder":false,"tags":[]},
  {"name":"Dinner, beef noodle, strained","kcal_100g":63.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Macaroni and cheese, toddler","kcal_100g":82.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Dinner, beef and rice, toddler","kcal_100g":82.0,"isPowder":false,"tags":["meat", "dinner", "toddler"]},
  {"name":"Dinner, beef with vegetables","kcal_100g":96.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, vegetables and lamb, junior","kcal_100g":51.0,"isPowder":false,"tags":["vegetable", "dinner"]},
  {"name":"Dinner, chicken noodle, strained","kcal_100g":74.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, chicken noodle, junior","kcal_100g":74.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, vegetables, noodles and chicken, junior","kcal_100g":64.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, pasta with vegetables","kcal_100g":60.0,"isPowder":false,"tags":["vegetable", "dinner"]},
  {"name":"Dinner, vegetables and noodles and turkey, strained","kcal_100g":44.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, vegetables and noodles and turkey, junior","kcal_100g":52.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, turkey and rice, strained","kcal_100g":52.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, macaroni and cheese, junior","kcal_100g":61.0,"isPowder":false,"tags":["dinner"]},
  {"name":"Vegetables, green beans, strained","kcal_100g":27.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, green beans, junior","kcal_100g":24.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Green beans, dices, toddler","kcal_100g":29.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Vegetables, squash, strained","kcal_100g":28.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, squash, junior","kcal_100g":24.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, sweet potatoes strained","kcal_100g":57.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, sweet potatoes, junior","kcal_100g":60.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Fruit, applesauce, junior","kcal_100g":37.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Fruit, apricot with tapioca, strained","kcal_100g":60.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Vegetables, corn, creamed, strained","kcal_100g":57.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Dinner, mixed vegetable, junior","kcal_100g":34.0,"isPowder":false,"tags":["vegetable", "dinner"]},
  {"name":"Fruit, bananas with tapioca, junior","kcal_100g":67.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Vegetables, mix vegetables junior","kcal_100g":36.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, garden vegetable, strained","kcal_100g":32.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Plums, bananas and rice, strained","kcal_100g":57.0,"isPowder":false,"tags":[]},
  {"name":"Dinner, turkey, rice, and vegetables, toddler","kcal_100g":60.0,"isPowder":false,"tags":["vegetable", "meat", "dinner", "toddler"]},
  {"name":"Dinner, apples and chicken, strained","kcal_100g":65.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, broccoli and chicken, junior","kcal_100g":62.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil Premature High Protein 24 Calori","kcal_100g":81.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil Premature 30 Calories, ready to ","kcal_100g":101.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil for Supplementing, powder, with ","kcal_100g":513.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil Reguline Powder, with ARA and DH","kcal_100g":513.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Pregestimil 24 Calories, ready to feed, ","kcal_100g":72.0,"isPowder":false,"tags":["formula"]},
  {"name":"Toddler drink, MEAD JOHNSON, PurAmino Toddler Powder, with ARA and DHA","kcal_100g":512.0,"isPowder":true,"tags":["toddler"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil for Supplementing, ready to feed","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Cereal, barley, prepared with whole milk","kcal_100g":84.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, with bananas, prepared with whole milk","kcal_100g":86.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, with honey, prepared with whole milk","kcal_100g":115.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, rice, prepared with whole milk","kcal_100g":85.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, rice, with honey, prepared with whole milk","kcal_100g":115.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, with iron, powder","kcal_100g":520.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Infant, with iron, powder, with","kcal_100g":511.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Infant, with iron, liquid conce","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL LIPIL, with iron, ready-to-feed,","kcal_100g":64.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, LIPIL, low iron, ready to feed,","kcal_100g":64.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, Infant, ready-to-feed, with ARA","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, PM 60/40, powder not recons","kcal_100g":524.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMIGEN WITH LGG, with iron,","kcal_100g":514.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMIGEN, with iron, ready-to","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ALIMENTUM, with iron, ready","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, ENFACARE, with iron, powder, wi","kcal_100g":505.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, with iron, liquid concentra","kcal_100g":127.0,"isPowder":false,"tags":["formula"]},
  {"name":"Child formula, ABBOTT NUTRITION, PEDIASURE, ready-to-feed","kcal_100g":99.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, NEXT STEP, PROSOBEE LIPIL, powder, with ","kcal_100g":480.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, NEXT STEP, PROSOBEE, LIPIL, ready to fee","kcal_100g":67.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, NESTLE, GOOD START SOY, with ARA and DHA, powder","kcal_100g":503.0,"isPowder":true,"tags":["formula"]},
  {"name":"Corn and sweet potatoes, strained","kcal_100g":68.0,"isPowder":false,"tags":[]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ALIMENTUM, ADVANCE, ready-t","kcal_100g":67.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, PBM PRODUCTS, store brand, ready-to-feed","kcal_100g":63.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, PBM PRODUCTS, store brand, liquid concentrate, not rec","kcal_100g":130.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, AR, ready-to-feed, with ARA and","kcal_100g":71.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, AR, powder, with ARA and DHA","kcal_100g":504.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC NEOSURE, ready-to-feed, with","kcal_100g":69.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, NEOSURE, powder, with ARA a","kcal_100g":520.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, SENSITIVE (LACTOSE FREE) re","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ADVANCE, with iron, liquid ","kcal_100g":127.0,"isPowder":false,"tags":["formula"]},
  {"name":"Clif Z bar","kcal_100g":416.0,"isPowder":false,"tags":[]},
  {"name":"Juice treats, fruit medley, toddler","kcal_100g":347.0,"isPowder":false,"tags":["juice", "fruit", "toddler"]},
  {"name":"Meat, beef, strained","kcal_100g":81.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, ham, junior","kcal_100g":97.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, lamb, strained","kcal_100g":94.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, lamb, junior","kcal_100g":112.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, chicken, strained","kcal_100g":130.0,"isPowder":false,"tags":["meat"]},
  {"name":"Meat, turkey sticks, junior","kcal_100g":188.0,"isPowder":false,"tags":["meat"]},
  {"name":"Snack, GERBER GRADUATE FRUIT STRIPS, Real Fruit Bars","kcal_100g":330.0,"isPowder":false,"tags":["fruit", "snack"]},
  {"name":"Meat, meat sticks, junior","kcal_100g":184.0,"isPowder":false,"tags":["meat"]},
  {"name":"Gerber 2nd Foods, apple, carrot and squash, organic","kcal_100g":64.0,"isPowder":false,"tags":[]},
  {"name":"Dinner, vegetables and dumplings and beef, junior","kcal_100g":48.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, beef lasagna, toddler","kcal_100g":77.0,"isPowder":false,"tags":["meat", "dinner", "toddler"]},
  {"name":"Dinner, macaroni and tomato and beef, strained","kcal_100g":61.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, macaroni and tomato and beef, junior","kcal_100g":59.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, spaghetti and tomato and meat, junior","kcal_100g":68.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, spaghetti and tomato and meat, toddler","kcal_100g":75.0,"isPowder":false,"tags":["meat", "dinner", "toddler"]},
  {"name":"Dinner, vegetables and beef, strained","kcal_100g":77.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, vegetables and beef, junior","kcal_100g":77.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, chicken soup, strained","kcal_100g":50.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, chicken stew, toddler","kcal_100g":78.0,"isPowder":false,"tags":["meat", "dinner", "toddler"]},
  {"name":"Dinner, vegetables chicken, strained","kcal_100g":59.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, vegetables, noodles and chicken, strained","kcal_100g":63.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, turkey and rice, junior","kcal_100g":56.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Dinner, vegetables and turkey, strained","kcal_100g":48.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, vegetables and turkey, junior","kcal_100g":53.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, macaroni and cheese, strained","kcal_100g":67.0,"isPowder":false,"tags":["dinner"]},
  {"name":"Vegetable, green beans and potatoes","kcal_100g":62.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, beets, strained","kcal_100g":34.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, carrots, strained","kcal_100g":26.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Vegetables, carrots, junior","kcal_100g":32.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Potatoes, toddler","kcal_100g":52.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Cereal, Oatmeal, dry, Gerber SINGLE GRAIN, fortified","kcal_100g":396.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Vegetable, butternut squash and corn","kcal_100g":50.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Apples, dices, toddler","kcal_100g":50.0,"isPowder":false,"tags":["toddler"]},
  {"name":"Fruit, applesauce, strained","kcal_100g":41.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Dinner, vegetables and chicken, junior","kcal_100g":53.0,"isPowder":false,"tags":["vegetable", "meat", "dinner"]},
  {"name":"Dinner, mixed vegetable, strained","kcal_100g":41.0,"isPowder":false,"tags":["vegetable", "dinner"]},
  {"name":"Vegetables, mix vegetables strained","kcal_100g":36.0,"isPowder":false,"tags":["vegetable"]},
  {"name":"Dinner, beef noodle, junior","kcal_100g":57.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Apples with ham, strained","kcal_100g":62.0,"isPowder":false,"tags":["meat"]},
  {"name":"Carrots and beef, strained","kcal_100g":59.0,"isPowder":false,"tags":["meat"]},
  {"name":"Beverage, Gerber Graduates FRUIT SPLASHERS","kcal_100g":29.0,"isPowder":false,"tags":["fruit"]},
  {"name":"Snack, Gerber Graduates YOGURT MELTS","kcal_100g":380.0,"isPowder":false,"tags":["dessert", "snack"]},
  {"name":"Dinner, sweet potatoes and chicken, strained","kcal_100g":74.0,"isPowder":false,"tags":["meat", "dinner"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil 24, ready to feed, with ARA and ","kcal_100g":71.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil Enspire Powder, with ARA and DHA","kcal_100g":514.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Enfamil Reguline, ready to feed, with AR","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, Gentlease, ready to feed, with ARA and D","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Toddler formula, MEAD JOHNSON, Nutramigen Toddler with LGG Powder, wit","kcal_100g":485.0,"isPowder":true,"tags":["formula", "toddler"]},
  {"name":"Infant formula, MEAD JOHNSON, Pregestimil 20 Calories, ready to feed, ","kcal_100g":69.0,"isPowder":false,"tags":["formula"]},
  {"name":"Cereal, high protein, prepared with whole milk","kcal_100g":111.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, mixed, prepared with whole milk","kcal_100g":96.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, mixed, with bananas, prepared with whole milk","kcal_100g":86.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, oatmeal, prepared with whole milk","kcal_100g":116.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, mixed, with honey, prepared with whole milk","kcal_100g":115.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, high protein, with apple and orange, prepared with whole milk","kcal_100g":112.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Cereal, rice, with bananas, prepared with whole milk","kcal_100g":86.0,"isPowder":false,"tags":["cereal"]},
  {"name":"Infant formula, NESTLE, GOOD START SUPREME, with iron, liquid concentr","kcal_100g":127.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, NESTLE, GOOD START SUPREME, with iron, powder","kcal_100g":509.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, LIPIL, low iron, liquid concent","kcal_100g":131.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, PREGESTIMIL, with iron, powder, with ARA","kcal_100g":517.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, PREGESTIMIL, with iron, with ARA and DHA","kcal_100g":67.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, PROSOBEE, with iron, ready-to-feed","kcal_100g":63.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ISOMIL, with iron, ready-to","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ISOMIL, with iron, liquid c","kcal_100g":128.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ISOMIL, with iron, powder, ","kcal_100g":517.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMIGEN, with iron, liquid c","kcal_100g":68.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, PROSOBEE, with iron, powder, no","kcal_100g":512.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, with iron, powder, not reco","kcal_100g":522.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, ENFAMIL, PROSOBEE, liquid concentrate, r","kcal_100g":67.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, PROSOBEE, with iron, ready to feed, with","kcal_100g":64.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, NESTLE, GOOD START SOY, with DHA and ARA, ready-to-fee","kcal_100g":64.0,"isPowder":false,"tags":["formula"]},
  {"name":"Child formula, ABBOTT NUTRITION, PEDIASURE, ready-to-feed, with iron a","kcal_100g":99.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, NESTLE, GOOD START ESSENTIALS SOY, with iron, powder","kcal_100g":502.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON, NEXT STEP PROSOBEE, powder, not reconsti","kcal_100g":480.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, MEAD JOHNSON,NEXT STEP PROSOBEE, prepared from powder","kcal_100g":67.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, PBM PRODUCTS, store brand, powder","kcal_100g":524.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, PBM PRODUCTS, store brand, soy, ready-to-feed","kcal_100g":63.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, PBM PRODUCTS, store brand, soy, liquid concentrate, no","kcal_100g":126.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, PBM PRODUCTS, store brand, soy, powder","kcal_100g":508.0,"isPowder":true,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, SENSITIVE, (LACTOSE FREE), ","kcal_100g":520.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ADVANCE, with iron, ready-t","kcal_100g":66.0,"isPowder":false,"tags":["formula"]},
  {"name":"Infant formula, ABBOTT NUTRITION, SIMILAC, ADVANCE, with iron, powder,","kcal_100g":522.0,"isPowder":true,"tags":["formula"]}
];

// ── Search foods by name fragment (case-insensitive), also matches tags ───
function searchBabyFoods(query) {
  if (!query || query.trim() === "") return BABY_FOODS.slice(0, 60);
  var q = query.toLowerCase();
  return BABY_FOODS.filter(function(f) {
    return f.name.toLowerCase().indexOf(q) !== -1 ||
      f.tags.some(function(t) { return t.indexOf(q) !== -1; });
  }).slice(0, 40);
}

// ── Get a food by exact name ──────────────────────────────────────────────
function babyFoodByName(name) {
  for (var i = 0; i < BABY_FOODS.length; i++) {
    if (BABY_FOODS[i].name === name) return BABY_FOODS[i];
  }
  return null;
}

// ── Feeding amount calculator ─────────────────────────────────────────────
function calcFeedingAmount(food, targetKcalPerDay, frequency) {
  if (!food || !isFinite(targetKcalPerDay) || targetKcalPerDay <= 0) return null;
  if (!frequency || frequency < 1) frequency = 3;

  var kcalPerG = food.kcal_100g / 100;
  var gramsPerDay = targetKcalPerDay / kcalPerG;
  var gramsPerFeed = gramsPerDay / frequency;
  var ozPerFeed = gramsPerFeed / 28.35;
  var mLPerFeed = gramsPerFeed;

  var freqLabels = {3: "TID", 4: "QID", 6: "q4h", 8: "q3h", 12: "q2h"};
  var freqLabel = freqLabels[frequency] || ("q" + Math.round(24/frequency) + "h x " + frequency);

  return {
    foodName: food.name,
    kcalPer100g: food.kcal_100g,
    isPowder: !!food.isPowder,
    targetKcalPerDay: Math.round(targetKcalPerDay),
    frequency: frequency,
    frequencyLabel: freqLabel,
    gramsPerDay: Math.round(gramsPerDay),
    gramsPerFeed: Math.round(gramsPerFeed),
    ozPerFeed: ozPerFeed,
    ozPerFeedRounded: ozPerFeed < 1 ? ozPerFeed.toFixed(1) : (Math.round(ozPerFeed) || "1"),
    mLPerFeed: Math.round(mLPerFeed)
  };
}

// ── Render feeding amount as HTML ─────────────────────────────────────────
function renderFeedingAmount(result) {
  if (!result) return "";
  var h = '<p><strong>' + escapeHtml(result.foodName) + '</strong> — ' +
    result.kcalPer100g + ' kcal/100g';
  if (result.isPowder) h += ' <span class="badge muted">powder</span>';
  h += '</p>';
  h += '<p>To meet <strong>' + result.targetKcalPerDay + ' kcal/day</strong> (' + result.frequencyLabel + '):</p>';
  h += '<ul style="font-size:.85rem;margin-bottom:.35rem">';
  h += '<li>' + result.gramsPerFeed + ' g per feed (' + result.gramsPerDay + ' g/day)</li>';
  h += '<li>' + result.ozPerFeedRounded + ' oz per feed</li>';
  h += '<li>' + result.mLPerFeed + ' mL per feed</li>';
  h += '</ul>';
  if (result.isPowder) {
    h += '<p class="disclaimer" style="font-size:.7rem;margin-top:0">Powder — reconstitute per label. Amount shown is for prepared formula.</p>';
  }
  return h;
}
